#pragma once

enum TEXTYPE	{ TEX_SINGLE, TEX_MULTI, TEX_END };

enum  OBJID     {  OBJ_PLAYER, OBJ_BULLET, OBJ_MONSTER, OBJ_MOUSE, OBJ_SHIELD, OBJ_UI, OBJ_END };

enum class PLAYER_STATE
{
	NONE = -1,
	IDLE,
	LEFT_RUN,
	UP_RUN,
	DOWN_RUN,
	LU_RUN,
	LD_RUN,

	END
};
